export type ColumnValue = string | number | boolean | null

export type TableRecord = {
    [k: string]: ColumnValue
}

export type DBTable<T extends TableRecord> = {
    [K in keyof T]: T[K]
}

export type TableStructure<T extends DBTable<TableRecord>> = {
    readonly id: (keyof T)[],
    readonly autogenerated: (keyof T)[],
}
