name: ${DOCKER_COMPOSE_NAME:?DOCKER_COMPOSE_NAME must be non-empty}

services:
  db:
    env_file: ${DB_ROOT?DB_ROOT must exist}/.env
    image: ${DOCKER_COMPOSE_NAME}/db
    container_name: ${DOCKER_COMPOSE_NAME}-db
    build:
      context: ${DB_ROOT}
    networks:
      - default
  app:
    depends_on:
      db:
        condition: service_healthy
    env_file: ${APP_ROOT?APP_ROOT must exist}/.env
    environment:
      - DB_HOST=db
    image: ${DOCKER_COMPOSE_NAME}/app
    container_name: ${DOCKER_COMPOSE_NAME}-app
    build:
      context: ${APP_ROOT}
      args:
        - WORKDIR=${DOCKER_WORKDIR?DOCKER_WORKDIR must exist}/app
        - USER=${DOCKER_USER:?DOCKER_USER must be non-empty}
        - APP_PORT=${APP_PORT:?APP_PORT must be non-empty}
    ports:
      - ${APP_PORT}:${APP_PORT}
    networks:
      - default

networks:
  default:
    driver: bridge
