DROP FUNCTION IF EXISTS PREFIX_UUID;
CREATE FUNCTION PREFIX_UUID (Prefix CHAR(3))
RETURNS VARCHAR(40)
NO SQL
BEGIN
    IF CHAR_LENGTH(Prefix) != 3 THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Prefix must be exactly 3 characters';
    END IF;
    RETURN CONCAT(Prefix, "-", UUID());
END;
